<script lang="ts">
  // Structured diff is preferred when backend supplies it; otherwise the
  // modal falls back to side-by-side plain-text columns. The exact diff
  // shape will be pinned by backend's T12 Activity Log entry.
  export type DiffSegment = {
    op: 'equal' | 'add' | 'remove' | 'replace';
    text: string;
  };

  type Props = {
    previous: string;
    proposed: string;
    diff?: DiffSegment[] | null;
    onClose: () => void;
  };
  let { previous, proposed, diff = null, onClose }: Props = $props();

  function handleScrim(e: MouseEvent) {
    if (e.target === e.currentTarget) onClose();
  }
  function handleScrimKey(e: KeyboardEvent) {
    if (e.target === e.currentTarget && (e.key === 'Enter' || e.key === ' ')) onClose();
  }
  function handleKey(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose();
  }
</script>

<svelte:window onkeydown={handleKey} />

<div
  class="dg-modal-scrim"
  onclick={handleScrim}
  onkeydown={handleScrimKey}
  role="dialog"
  aria-modal="true"
  aria-label="Relationship context diff"
  tabindex="-1"
>
  <div class="dg-modal rcdiff-modal">
    <header class="dg-modal-head">
      <h3>Rel context · <span style="color: var(--mash-pulp);">view diff</span></h3>
      <button type="button" class="x" onclick={onClose} aria-label="Close">✕</button>
    </header>

    <div class="dg-modal-body">
      {#if diff && diff.length}
        <span class="dg-modal-eyebrow">Proposed changes</span>
        <div class="rcdiff-stream">
          {#each diff as seg, i (i)}
            <span class="rcdiff-seg rcdiff-seg--{seg.op}">{seg.text}</span>
          {/each}
        </div>
      {:else}
        <div class="rcdiff-cols">
          <div class="rcdiff-col">
            <span class="dg-modal-eyebrow">Previous</span>
            <pre class="rcdiff-text rcdiff-text--prev">{previous || '(empty)'}</pre>
          </div>
          <div class="rcdiff-col">
            <span class="dg-modal-eyebrow">Proposed</span>
            <pre class="rcdiff-text rcdiff-text--next">{proposed || '(empty)'}</pre>
          </div>
        </div>
      {/if}
      <p class="dg-modal-hint">
        The proposed rel context was generated by the finalize-time LLM pass over the digest. Accepting it is currently a backend follow-up.
      </p>
    </div>

    <footer class="dg-modal-foot">
      <span class="cost">read-only · accept/revert lands with backend T12 follow-on</span>
      <button type="button" class="mash-btn mash-btn--ghost mash-btn--sm" onclick={onClose}>Close</button>
    </footer>
  </div>
</div>

<style>
  .rcdiff-modal {
    max-width: 920px;
    width: min(94vw, 920px);
  }
  .rcdiff-cols {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
  }
  .rcdiff-col {
    display: flex;
    flex-direction: column;
    gap: 6px;
    min-width: 0;
  }
  .rcdiff-text {
    margin: 0;
    padding: 12px;
    border: 1px solid var(--line);
    border-radius: var(--r-2);
    background: var(--ink-0);
    font: 400 12.5px/1.55 var(--font-mono);
    color: var(--fg-2);
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 50vh;
    overflow-y: auto;
  }
  .rcdiff-text--prev { border-left: 2px solid var(--ink-3); }
  .rcdiff-text--next { border-left: 2px solid var(--moss); }

  .rcdiff-stream {
    padding: 12px;
    border: 1px solid var(--line);
    border-radius: var(--r-2);
    background: var(--ink-0);
    font: 400 12.5px/1.6 var(--font-mono);
    color: var(--fg-2);
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 50vh;
    overflow-y: auto;
  }
  .rcdiff-seg--equal { color: var(--fg-2); }
  .rcdiff-seg--add {
    background: rgba(126, 168, 100, 0.18);
    color: var(--moss, #7ea864);
    text-decoration: none;
  }
  .rcdiff-seg--remove {
    background: rgba(208, 90, 70, 0.18);
    color: var(--ember, #d05a46);
    text-decoration: line-through;
  }
  .rcdiff-seg--replace {
    background: rgba(210, 148, 0, 0.18);
    color: var(--amber, #d29400);
  }
</style>
