<script lang="ts">
  // Structured diff is preferred when backend supplies it; otherwise the
  // modal falls back to side-by-side plain-text columns. The exact diff
  // shape will be pinned by backend's T12 Activity Log entry.
  export type DiffSegment = {
    op: 'equal' | 'add' | 'remove' | 'replace';
    text: string;
  };

  type Props = {
    previous: string;
    proposed: string;
    leagueId: number;
    diff?: DiffSegment[] | null;
    onClose: () => void;
    onSaved?: (newContext: string) => void;
    onPatchError?: (message: string) => void;
  };
  let {
    previous,
    proposed,
    leagueId,
    diff = null,
    onClose,
    onSaved,
    onPatchError,
  }: Props = $props();

  let patching = $state(false);

  function handleScrim(e: MouseEvent) {
    if (e.target === e.currentTarget && !patching) onClose();
  }
  function handleScrimKey(e: KeyboardEvent) {
    if (e.target === e.currentTarget && !patching && (e.key === 'Enter' || e.key === ' ')) onClose();
  }
  function handleKey(e: KeyboardEvent) {
    if (e.key === 'Escape' && !patching) onClose();
  }

  async function patchContext(target: 'proposed' | 'previous') {
    const body = target === 'proposed' ? proposed : previous;
    const label = target === 'proposed' ? 'Accept proposed' : 'Revert to previous';
    if (!confirm(`${label}? This writes the chosen text to the league's rel context.`)) return;

    patching = true;
    try {
      const res = await fetch(`/api/leagues/${leagueId}/rel-context`, {
        method: 'PATCH',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ context: body }),
      });
      if (!res.ok) {
        const text = await res.text().catch(() => '');
        throw new Error(`PATCH failed (${res.status}) ${text.slice(0, 200)}`);
      }
      onSaved?.(body);
    } catch (err) {
      onPatchError?.(err instanceof Error ? err.message : String(err));
    } finally {
      patching = false;
    }
  }
</script>

<svelte:window onkeydown={handleKey} />

<div
  class="dg-modal-scrim"
  onclick={handleScrim}
  onkeydown={handleScrimKey}
  role="dialog"
  aria-modal="true"
  aria-label="Relationship context diff"
  tabindex="-1"
>
  <div class="dg-modal rcdiff-modal">
    <header class="dg-modal-head">
      <h3>Rel context · <span style="color: var(--mash-pulp);">view diff</span></h3>
      <button type="button" class="x" onclick={onClose} aria-label="Close">✕</button>
    </header>

    <div class="dg-modal-body">
      {#if diff && diff.length}
        <span class="dg-modal-eyebrow">Proposed changes</span>
        <div class="rcdiff-stream">
          {#each diff as seg, i (i)}
            <span class="rcdiff-seg rcdiff-seg--{seg.op}">{seg.text}</span>
          {/each}
        </div>
      {:else}
        <div class="rcdiff-cols">
          <div class="rcdiff-col">
            <span class="dg-modal-eyebrow">Previous</span>
            <pre class="rcdiff-text rcdiff-text--prev">{previous || '(empty)'}</pre>
          </div>
          <div class="rcdiff-col">
            <span class="dg-modal-eyebrow">Proposed</span>
            <pre class="rcdiff-text rcdiff-text--next">{proposed || '(empty)'}</pre>
          </div>
        </div>
      {/if}
      <p class="dg-modal-hint">
        The proposed rel context was generated by the finalize-time LLM pass over the digest. Accepting it is currently a backend follow-up.
      </p>
    </div>

    <footer class="dg-modal-foot">
      <span class="cost">{patching ? 'saving…' : `${proposed.length} chars proposed · ${previous.length} chars previous`}</span>
      <div style="display: flex; gap: 8px;">
        <button type="button" class="mash-btn mash-btn--ghost mash-btn--sm" onclick={onClose} disabled={patching}>Close</button>
        <button type="button" class="mash-btn mash-btn--secondary mash-btn--sm" onclick={() => patchContext('previous')} disabled={patching}>↺ Revert to previous</button>
        <button type="button" class="mash-btn mash-btn--primary mash-btn--sm" onclick={() => patchContext('proposed')} disabled={patching}>✓ Accept proposed</button>
      </div>
    </footer>
  </div>
</div>

<style>
  .rcdiff-modal {
    max-width: 920px;
    width: min(94vw, 920px);
  }
  .rcdiff-cols {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
  }
  .rcdiff-col {
    display: flex;
    flex-direction: column;
    gap: 6px;
    min-width: 0;
  }
  .rcdiff-text {
    margin: 0;
    padding: 12px;
    border: 1px solid var(--line);
    border-radius: var(--r-2);
    background: var(--ink-0);
    font: 400 12.5px/1.55 var(--font-mono);
    color: var(--fg-2);
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 50vh;
    overflow-y: auto;
  }
  .rcdiff-text--prev { border-left: 2px solid var(--ink-3); }
  .rcdiff-text--next { border-left: 2px solid var(--moss); }

  .rcdiff-stream {
    padding: 12px;
    border: 1px solid var(--line);
    border-radius: var(--r-2);
    background: var(--ink-0);
    font: 400 12.5px/1.6 var(--font-mono);
    color: var(--fg-2);
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 50vh;
    overflow-y: auto;
  }
  .rcdiff-seg--equal { color: var(--fg-2); }
  .rcdiff-seg--add {
    background: rgba(126, 168, 100, 0.18);
    color: var(--moss, #7ea864);
    text-decoration: none;
  }
  .rcdiff-seg--remove {
    background: rgba(208, 90, 70, 0.18);
    color: var(--ember, #d05a46);
    text-decoration: line-through;
  }
  .rcdiff-seg--replace {
    background: rgba(210, 148, 0, 0.18);
    color: var(--amber, #d29400);
  }
</style>
